---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: ruff
        name: Lint and format with Ruff
        entry: uv run ruff
        language: system
        pass_filenames: false
        always_run: true
        args: ["check", "rest_angular", "tests", "--fix"]

      - id: pyright
        name: Type check with pyright
        entry: uv run pyright
        language: system
        pass_filenames: false
        always_run: true
        args: []
