services:
  api:
    build:
      context: .
    env_file:
      - .env
    volumes:
      # Adds current directory as volume.
      - .:/app/src/
    environment:
      # Enables autoreload.
      RELOAD: "True"
