name: Testing rest_angular

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: uv sync
      - name: Run lint check
        run: uv run pre-commit
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env
        run: touch .env
      - name: Update docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "2.28.0"
      - name: Run tests with Docker Compose
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml run --build --rm api
